"""Pydantic schemas for the Planning Agent pipeline."""
from __future__ import annotations

from typing import Any, Literal, Optional

from pydantic import BaseModel, Field

from src.common.schemas import FilterCriteria


class SearchQueryDraft(BaseModel):
    """Single search query with optional filters."""
    text: str = Field(..., description="Refined search sentence for vector search")
    filters: Optional[FilterCriteria] = Field(None, description="Metadata filters (year, author, etc.)")
    top_k: int = Field(5, description="Number of results to retrieve")


class CollectionSearchPlan(BaseModel):
    """Search plan for a single collection."""
    collection: str = Field(..., description="Collection name to search")
    mode: Literal["parallel", "sequential"] = Field("parallel", description="Execution mode")
    priority: int = Field(1, description="Execution priority (lower = first)")
    query_drafts: list[SearchQueryDraft] = Field(..., description="Alternative search queries")


class SearchPlan(BaseModel):
    """Complete search plan generated by the Planning Agent."""
    intent: Literal["factual", "comparative", "analytical", "temporal", "unknown"] = Field(
        ..., description="Query intent classification"
    )
    query_type: Literal["fact", "summary", "comparison", "reasoning", "policy"] = Field(
        "fact", description="Query type drives allocator budgets"
    )
    resources: list[CollectionSearchPlan] = Field(
        ..., description="Collections to search with query drafts"
    )
    reasoning: str = Field(..., description="Why this plan was chosen")


class ValidationResult(BaseModel):
    """Output validation result from the Sanitizer Agent."""
    passes: bool = Field(..., description="Whether the answer passes all checks")
    checks: dict[str, bool] = Field(
        default_factory=dict,
        description="Individual check results: {check_name: passed}"
    )
    issues: list[str] = Field(
        default_factory=list,
        description="List of issues found (empty if passes)"
    )
    retry_hint: Optional[str] = Field(None, description="Hint for retry if validation failed")
    corrected_answer: Optional[str] = Field(
        None,
        description="Sanitizer's corrected answer produced in the same validation call (None if unchanged)"
    )


class BadWordsResult(BaseModel):
    """Output of the BadWordsFilter (no LLM)."""
    matched: bool = Field(..., description="True if any bad word or pattern matched")
    matched_terms: list[str] = Field(
        default_factory=list,
        description="Matched terms, surfaced in the trace only; never echoed to the user",
    )


class ScopeResult(BaseModel):
    """Output of the ScopeClassifier LLM call."""
    scope: Literal["in_scope", "off_domain"] = Field(..., description="Scope classification")
    confidence: float = Field(..., description="Classifier confidence in [0, 1]", ge=0.0, le=1.0)
    reason: str = Field(default="", description="Short Turkish rationale, surfaced in trace")


class SuggestionList(BaseModel):
    """Output of the Suggester LLM call."""
    suggestions: list[str] = Field(
        ...,
        description="In-domain Turkish queries returned by the Suggester LLM. Target 3 after Suggester normalization; schema allows 1..10 for fault tolerance.",
        min_length=1,
        max_length=10,
    )


class AgentTraceEvent(BaseModel):
    """Single trace event from the pipeline."""
    trace_id: str = Field(..., description="Unique trace ID for the query")
    phase: str = Field(..., description="Pipeline phase: planning, retrieval, re_retrieval, answering, validation")
    block: Optional[str] = Field(None, description="Deployment block used (e.g. fast-01)")
    model: Optional[str] = Field(None, description="Model used")
    latency_ms: float = Field(..., description="Phase latency in milliseconds")
    details: dict[str, Any] = Field(
        default_factory=dict,
        description="Phase-specific metadata (intent, result_count, etc.)"
    )


class AgentOutput(BaseModel):
    """Final output from the Planning Agent pipeline."""
    answer: str = Field(..., description="Generated answer text")
    thinking: str = Field(default="", description="LLM thinking/reasoning text")
    scope: Literal["in_scope", "off_domain", "bad_word"] = Field(
        default="in_scope",
        description="Pre-planner gate classification; controls UI rendering",
    )
    suggestions: list[str] = Field(
        default_factory=list,
        description="Populated only when scope='off_domain'",
    )
    plan: Optional[SearchPlan] = Field(None, description="The search plan that was executed")
    validation: Optional[ValidationResult] = Field(None, description="Output validation result")
    trace: list[AgentTraceEvent] = Field(
        default_factory=list,
        description="Pipeline trace events",
    )
    sources: list[dict] = Field(
        default_factory=list,
        description="Retrieved source metadata",
    )
    re_retrieved: bool = Field(False, description="Deprecated; always False under orchestrator path")
    quality_re_retrieved: bool = Field(False, description="Deprecated; always False under orchestrator path")

    # New orchestrator fields (all optional for backwards-compat with legacy path)
    policy_result: Optional[PolicyResult] = Field(None, description="Policy gating result (orchestrator path)")
    evidence_decision: Optional[EvidenceDecision] = Field(None, description="EvidenceJudge final decision (orchestrator path)")
    assembly: list[ContextAssemblyItem] = Field(default_factory=list, description="Assembled context slot provenance (orchestrator path)")
    expanded: bool = Field(False, description="True when expansion ran (orchestrator path)")


class Chunk(BaseModel):
    """A retrieved chunk attributed to its source collection."""
    chunk_id: str = Field(..., description="Stable chunk identifier")
    document_id: str = Field(..., description="Source document identifier")
    collection_name: str = Field(..., description="Source collection key")
    doc_type: str = Field(..., description="Document type label (e.g. gazete, tutanak)")
    source_title: str = Field(..., description="Human-readable source title")
    text: str = Field(..., description="Chunk body text")
    score: float = Field(..., description="Initial retrieval score (cosine 1-distance)")
    rerank_score: float = Field(0.0, description="Cross-encoder rerank score; defaults to score when not reranked")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Source metadata pass-through")


class RetrievalOutput(BaseModel):
    """Per-collection retrieval result with primary and reserve buffers."""
    collection_name: str = Field(..., description="Source collection key")
    chunks: list[Chunk] = Field(default_factory=list, description="Primary chunks consumed by the assembler")
    reserve_chunks: list[Chunk] = Field(default_factory=list, description="Held-back candidates released on expand")
    fetched_count: int = Field(..., description="Total chunks fetched from vector search")
    returned_count: int = Field(..., description="Count placed in `chunks` (primary buffer)")
    latency_ms: float = Field(..., description="Wall-clock retrieval latency")
    filter_applied: dict[str, Any] = Field(default_factory=dict, description="Filter dict actually applied")


class PolicyResult(BaseModel):
    """Result of policy enforcement on planner-suggested collections."""
    allowed_collections: list[str] = Field(..., description="Collections that passed policy gating")
    denied_collections: list[str] = Field(default_factory=list, description="Collections suggested by planner but blocked by policy")
    reason_by_collection: dict[str, str] = Field(default_factory=dict, description="Map of denied collection name to reason code")


class CollectionExecutionPlan(BaseModel):
    """Per-collection execution plan with primary + reserve budgets."""
    collection_name: str = Field(..., description="Target collection key")
    priority: int = Field(1, description="Execution order (lower = first)")
    retrieval_budget: int = Field(..., description="Primary slots assembled into context")
    reserve_budget: int = Field(..., description="Held-back slots released on expand")
    fetch_k: int = Field(..., description="Vector top-N (must be >= primary + reserve)")
    filters: dict[str, Any] = Field(default_factory=dict, description="Metadata filters applied to retrieval")
    enabled: bool = Field(True, description="If false, retrieval is skipped for this collection")
    route_reason: str = Field("", description="Why this collection was chosen")


class ContextAssemblyItem(BaseModel):
    """One slot in the assembled context with provenance."""
    chunk_id: str = Field(..., description="Chunk identifier")
    collection_name: str = Field(..., description="Source collection key")
    document_id: str = Field(..., description="Source document identifier")
    slot_type: Literal["primary", "supporting", "diversity", "reserve"] = Field(..., description="Slot category in assembled context")
    assembly_reason: str = Field(..., description="Why this slot was filled by this chunk")
    order_index: int = Field(..., description="Position in the assembled context")


class EvidenceDecision(BaseModel):
    """EvidenceJudge output controlling next pipeline step."""
    sufficient: bool = Field(..., description="True when assembled chunks are deemed enough to answer")
    confidence: float = Field(..., description="Confidence in the decision in [0,1]")
    missing_aspects: list[str] = Field(default_factory=list, description="What is missing when not sufficient")
    action: Literal["answer", "expand", "clarify", "refuse"] = Field(..., description="Next step the orchestrator must take")
    judge_type: Literal["heuristic", "llm"] = Field("heuristic", description="Which decision path produced this")


class OrchestratorState(BaseModel):
    """Full state passed across orchestrator stages."""
    request_id: str = Field(..., description="Unique per-request identifier")
    user_query: str = Field(..., description="Raw user query")
    normalized_query: str = Field("", description="Optionally normalized query text")
    planner_output: Optional[SearchPlan] = Field(None, description="Plan returned by the Planner stage")
    policy_result: Optional[PolicyResult] = Field(None, description="Result of policy gating")
    collection_plans: list[CollectionExecutionPlan] = Field(default_factory=list, description="Per-collection execution plans")
    retrieval_results: dict[str, RetrievalOutput] = Field(default_factory=dict, description="Retrieval output keyed by collection name")
    assembled_chunks: list[Chunk] = Field(default_factory=list, description="Chunks placed into primary context slots")
    balanced_context: list[ContextAssemblyItem] = Field(default_factory=list, description="Slot-level provenance for assembled context")
    evidence_decision: Optional[EvidenceDecision] = Field(None, description="Latest EvidenceJudge decision")
    expanded: bool = Field(False, description="True when ExpansionPlanner consumed reserves")
    final_answer: str = Field("", description="Generated answer text")
    citations: list[dict[str, Any]] = Field(default_factory=list, description="Citation dicts produced by CitationBuilder")
    trace: list[AgentTraceEvent] = Field(default_factory=list, description="Per-stage trace events")
    errors: list[str] = Field(default_factory=list, description="Non-fatal error codes collected during the run")
