"""Pydantic schemas for the Planning Agent pipeline."""
from __future__ import annotations

from typing import Any, Literal, Optional

from pydantic import BaseModel, Field

from src.common.schemas import FilterCriteria


class SearchQueryDraft(BaseModel):
    """Single search query with optional filters."""
    text: str = Field(..., description="Refined search sentence for vector search")
    filters: Optional[FilterCriteria] = Field(None, description="Metadata filters (year, author, etc.)")
    top_k: int = Field(10, description="Number of results to retrieve")


class CollectionSearchPlan(BaseModel):
    """Search plan for a single collection."""
    collection: str = Field(..., description="Collection name to search")
    mode: Literal["parallel", "sequential"] = Field("parallel", description="Execution mode")
    priority: int = Field(1, description="Execution priority (lower = first)")
    query_drafts: list[SearchQueryDraft] = Field(..., description="Alternative search queries")


class TermHypothesis(BaseModel):
    """A re-query LLM's guess at a domain-specific/formal synonym for a term in
    the query that may not match the corpus's own phrasing in embedding space
    (e.g. 'kadük' -> 'hükümsüz sayılan kanun teklifleri'). Purely additive: the
    hypothesis becomes one more query draft alongside the existing broadened
    drafts (RRF-fusion handles a wrong guess with zero downside — it just
    doesn't help). Surfaced to a human for review via the term_candidates table
    (src/api/db.py) when a round using it actually succeeds."""
    term: str = Field(..., description="The suspected jargon/colloquial term from the query")
    official_phrase: str = Field(..., description="LLM's guess at the formal/official corpus phrasing")


class SearchPlan(BaseModel):
    """Complete search plan generated by the Planning Agent."""
    intent: Literal["factual", "comparative", "analytical", "temporal", "unknown"] = Field(
        ..., description="Query intent classification"
    )
    query_type: Literal["fact", "summary", "comparison", "reasoning", "policy", "comprehensive"] = Field(
        "fact", description="Query type drives retrieval budgets; 'comprehensive' = "
        "enumeration/exhaustive queries that gather many chunks across iterative rounds",
    )
    strategy: Optional[str] = Field(
        None,
        description="Selected research strategy name from the research_strategies.md "
        "playbook (e.g. 'enumerate', 'summarize'); resolved by the orchestrator into "
        "a query_type + answer_directive override. None when the playbook is empty "
        "or the LLM didn't pick one.",
    )
    resources: list[CollectionSearchPlan] = Field(
        ..., description="Collections to search with query drafts"
    )
    reasoning: str = Field(..., description="Why this plan was chosen")
    refined_query: Optional[str] = Field(
        None,
        description="Query with filter words stripped (from FilterExtractor); "
        "used as the orchestrator retrieval query text",
    )
    term_hypothesis: Optional[TermHypothesis] = Field(
        None,
        description="Re-query LLM's guess at an official/formal synonym for a "
        "possibly-jargon term in the query; only ever produced on a broaden() "
        "re-query call, never the initial plan. None when no hypothesis was made.",
    )


class ValidationResult(BaseModel):
    """Output validation result from the Sanitizer Agent."""
    passes: bool = Field(..., description="Whether the answer passes all checks")
    checks: dict[str, bool] = Field(
        default_factory=dict,
        description="Individual check results: {check_name: passed}"
    )
    issues: list[str] = Field(
        default_factory=list,
        description="List of issues found (empty if passes)"
    )
    retry_hint: Optional[str] = Field(None, description="Hint for retry if validation failed")
    corrected_answer: Optional[str] = Field(
        None,
        description="Sanitizer's corrected answer produced in the same validation call (None if unchanged)"
    )


class BadWordsResult(BaseModel):
    """Output of the BadWordsFilter (no LLM)."""
    matched: bool = Field(..., description="True if any bad word or pattern matched")
    matched_terms: list[str] = Field(
        default_factory=list,
        description="Matched terms, surfaced in the trace only; never echoed to the user",
    )


class ScopeResult(BaseModel):
    """Output of the IntentAnalyzer (extended ScopeClassifier) LLM call."""
    scope: Literal["in_scope", "off_domain", "conversational"] = Field(..., description="Scope classification")
    confidence: float = Field(..., description="Classifier confidence in [0, 1]", ge=0.0, le=1.0)
    selected_collections: list[str] = Field(
        default_factory=list,
        description="Tool/db selection: collection keys the intent points to. "
        "Empty → planner selects freely from the full catalog (fail-open).",
    )
    reason: str = Field(default="", description="Short Turkish rationale, surfaced in trace")


class FacetValue(BaseModel):
    """A single mined facet value with its frequency in the probe results."""
    value: str = Field(..., description="Facet value (e.g. '1997', 'bütçe', 'Hürriyet')")
    count: int = Field(..., description="How many probe hits carried this value")


class FacetSet(BaseModel):
    """Deterministically mined facets from the probe-retrieval metadata."""
    years: list[FacetValue] = Field(default_factory=list, description="Distinct years, most frequent first")
    topics: list[FacetValue] = Field(default_factory=list, description="Distinct topics, most frequent first")
    authors: list[FacetValue] = Field(default_factory=list, description="Distinct authors/speakers, most frequent first")
    collections: list[FacetValue] = Field(default_factory=list, description="Distinct source collections")
    total: int = Field(0, description="Number of probe hits the facets were mined from")


class ClarificationQuestion(BaseModel):
    """One grounded did-you-mean question phrased from mined facets."""
    axis: Literal["year", "scope", "topic"] = Field(..., description="Which dimension this narrows")
    text: str = Field(..., description="Question text shown to the user")
    options: list[str] = Field(default_factory=list, description="Facet-grounded answer options (real values only)")


class ClarificationResult(BaseModel):
    """Outcome of the clarification stage (interactive or auto)."""
    asked: bool = Field(False, description="True when questions were put to the user")
    auto_applied: bool = Field(False, description="True when the strongest facet was auto-applied (non-interactive)")
    turns: int = Field(0, description="How many clarification turns ran")
    questions: list[ClarificationQuestion] = Field(default_factory=list, description="Questions generated this run")
    # Resolved constraints
    year: Optional[int] = Field(None, description="Chosen year → FilterCriteria.year")
    collections: list[str] = Field(default_factory=list, description="Chosen collection narrowing")
    topic: Optional[str] = Field(None, description="Chosen topic → appended to the search query")
    note: str = Field("", description="Assumption note surfaced to the user (auto path)")


class SuggestionList(BaseModel):
    """Output of the Suggester LLM call."""
    suggestions: list[str] = Field(
        ...,
        description="In-domain Turkish queries returned by the Suggester LLM. Target 3 after Suggester normalization; schema allows 1..10 for fault tolerance.",
        min_length=1,
        max_length=10,
    )


class AgentTraceEvent(BaseModel):
    """Single trace event from the pipeline."""
    trace_id: str = Field(..., description="Unique trace ID for the query")
    phase: str = Field(..., description="Pipeline phase: planning, retrieval, re_retrieval, answering, validation")
    block: Optional[str] = Field(None, description="Deployment block used (e.g. fast-01)")
    model: Optional[str] = Field(None, description="Model used")
    latency_ms: float = Field(..., description="Phase latency in milliseconds")
    details: dict[str, Any] = Field(
        default_factory=dict,
        description="Phase-specific metadata (intent, result_count, etc.)"
    )


class AgentOutput(BaseModel):
    """Final output from the Planning Agent pipeline."""
    answer: str = Field(..., description="Generated answer text")
    thinking: str = Field(default="", description="LLM thinking/reasoning text")
    scope: Literal["in_scope", "off_domain", "bad_word", "conversational"] = Field(
        default="in_scope",
        description="Pre-planner gate classification; controls UI rendering",
    )
    suggestions: list[str] = Field(
        default_factory=list,
        description="Populated only when scope='off_domain'",
    )
    rabbit_holes: list[str] = Field(
        default_factory=list,
        description="Facet-grounded drill-down suggestions for broad/ambiguous "
        "in-scope queries (shown as clickable chips); also mirrors off_domain "
        "suggestions so the UI renders one chip mechanism for both.",
    )
    plan: Optional[SearchPlan] = Field(None, description="The search plan that was executed")
    validation: Optional[ValidationResult] = Field(None, description="Output validation result")
    trace: list[AgentTraceEvent] = Field(
        default_factory=list,
        description="Pipeline trace events",
    )
    sources: list[dict] = Field(
        default_factory=list,
        description="Retrieved source metadata",
    )
    re_retrieved: bool = Field(False, description="Deprecated; always False under orchestrator path")
    quality_re_retrieved: bool = Field(False, description="Deprecated; always False under orchestrator path")

    # New orchestrator fields (all optional for backwards-compat with legacy path)
    policy_result: Optional[PolicyResult] = Field(None, description="Policy gating result (orchestrator path)")
    evidence_decision: Optional[EvidenceDecision] = Field(None, description="EvidenceJudge final decision (orchestrator path)")
    assembly: list[ContextAssemblyItem] = Field(default_factory=list, description="Assembled context slot provenance (orchestrator path)")
    expanded: bool = Field(False, description="True when expansion ran (orchestrator path)")
    clarification: Optional[ClarificationResult] = Field(None, description="Clarification stage outcome (orchestrator path)")


class Chunk(BaseModel):
    """A retrieved chunk attributed to its source collection."""
    chunk_id: str = Field(..., description="Stable chunk identifier")
    document_id: str = Field(..., description="Source document identifier")
    collection_name: str = Field(..., description="Source collection key")
    doc_type: str = Field(..., description="Document type label (e.g. gazete, tutanak)")
    source_title: str = Field(..., description="Human-readable source title")
    text: str = Field(..., description="Chunk body text")
    score: float = Field(..., description="Initial retrieval score (cosine 1-distance)")
    rerank_score: float = Field(0.0, description="Cross-encoder rerank score; defaults to score when not reranked")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Source metadata pass-through")


class RetrievalOutput(BaseModel):
    """Per-collection retrieval result."""
    collection_name: str = Field(..., description="Source collection key")
    chunks: list[Chunk] = Field(default_factory=list, description="Chunks consumed by the assembler")
    fetched_count: int = Field(..., description="Total chunks fetched from vector search")
    returned_count: int = Field(..., description="Count placed in `chunks` (primary buffer)")
    latency_ms: float = Field(..., description="Wall-clock retrieval latency")
    filter_applied: dict[str, Any] = Field(default_factory=dict, description="Filter dict actually applied")


class PolicyResult(BaseModel):
    """Result of policy enforcement on planner-suggested collections."""
    allowed_collections: list[str] = Field(..., description="Collections that passed policy gating")
    denied_collections: list[str] = Field(default_factory=list, description="Collections suggested by planner but blocked by policy")
    reason_by_collection: dict[str, str] = Field(default_factory=dict, description="Map of denied collection name to reason code")


class CollectionExecutionPlan(BaseModel):
    """Per-collection execution plan with a retrieval budget."""
    collection_name: str = Field(..., description="Target collection key")
    priority: int = Field(1, description="Execution order (lower = first)")
    retrieval_budget: int = Field(..., description="Slots assembled into context")
    fetch_k: int = Field(..., description="Vector top-N (must be >= retrieval_budget)")
    filters: dict[str, Any] = Field(default_factory=dict, description="Metadata filters applied to retrieval")
    query_drafts: list[str] = Field(
        default_factory=list,
        description="Planner query rewrites for this collection; each is run as a "
        "separate parallel search and the ranked lists are RRF-fused. Empty list "
        "→ retrieval falls back to the raw user query.",
    )
    enabled: bool = Field(True, description="If false, retrieval is skipped for this collection")
    route_reason: str = Field("", description="Why this collection was chosen")


class ContextAssemblyItem(BaseModel):
    """One slot in the assembled context with provenance."""
    chunk_id: str = Field(..., description="Chunk identifier")
    collection_name: str = Field(..., description="Source collection key")
    document_id: str = Field(..., description="Source document identifier")
    slot_type: Literal["primary", "supporting", "diversity"] = Field(..., description="Slot category in assembled context")
    assembly_reason: str = Field(..., description="Why this slot was filled by this chunk")
    order_index: int = Field(..., description="Position in the assembled context")


class EvidenceDecision(BaseModel):
    """EvidenceJudge output controlling next pipeline step."""
    sufficient: bool = Field(..., description="True when assembled chunks are deemed enough to answer")
    confidence: float = Field(..., description="Confidence in the decision in [0,1]")
    missing_aspects: list[str] = Field(default_factory=list, description="What is missing when not sufficient")
    action: Literal["answer", "expand", "clarify", "refuse"] = Field(..., description="Next step the orchestrator must take")
    judge_type: Literal["heuristic", "llm"] = Field("heuristic", description="Which decision path produced this")
    reasoning: str = Field("", description="Short Turkish rationale for the decision (surfaced per-stage in the UI)")


class OrchestratorState(BaseModel):
    """Full state passed across orchestrator stages."""
    request_id: str = Field(..., description="Unique per-request identifier")
    user_query: str = Field(..., description="Raw user query")
    normalized_query: str = Field("", description="Optionally normalized query text")
    planner_output: Optional[SearchPlan] = Field(None, description="Plan returned by the Planner stage")
    policy_result: Optional[PolicyResult] = Field(None, description="Result of policy gating")
    collection_plans: list[CollectionExecutionPlan] = Field(default_factory=list, description="Per-collection execution plans")
    retrieval_results: dict[str, RetrievalOutput] = Field(default_factory=dict, description="Retrieval output keyed by collection name")
    assembled_chunks: list[Chunk] = Field(default_factory=list, description="Chunks placed into primary context slots")
    balanced_context: list[ContextAssemblyItem] = Field(default_factory=list, description="Slot-level provenance for assembled context")
    evidence_decision: Optional[EvidenceDecision] = Field(None, description="Latest EvidenceJudge decision")
    expanded: bool = Field(False, description="True when a re-query expansion added chunks")
    expand_iterations: int = Field(0, description="How many bounded re-query expansions have run")
    tried_searches: dict[str, int] = Field(
        default_factory=dict,
        description="Ledger of already-executed searches: JSON key "
        "[collection, query_text, filters] → deepest fetch_k tried. Expansion "
        "rounds prune drafts already searched at this-or-greater depth (ANN is "
        "deterministic, so re-running them cannot add chunks).",
    )
    facets: Optional[FacetSet] = Field(None, description="Facets mined from the probe retrieval")
    rabbit_holes: list[str] = Field(default_factory=list, description="Facet-grounded drill-down suggestions for broad/ambiguous queries")
    clarification: Optional[ClarificationResult] = Field(None, description="Clarification stage outcome")
    applied_constraints: dict[str, Any] = Field(default_factory=dict, description="Constraints applied from clarification (year/collections/topic)")
    clarify_turns: int = Field(0, description="Clarification turns consumed")
    selected_collections: list[str] = Field(default_factory=list, description="Tool/db selection from IntentAnalyzer")
    answer_directive: Optional[str] = Field(
        None,
        description="Resolved research_strategies.md answer_directive for the "
        "selected strategy; appended to the answering system prompt when set",
    )
    final_answer: str = Field("", description="Generated answer text")
    citations: list[dict[str, Any]] = Field(default_factory=list, description="Citation dicts produced by CitationBuilder")
    trace: list[AgentTraceEvent] = Field(default_factory=list, description="Per-stage trace events")
    errors: list[str] = Field(default_factory=list, description="Non-fatal error codes collected during the run")
